---
- name: Launch AAP Job Template
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    env: "{{ lookup('env', 'ENV') }}"
    cluster: "{{ lookup('env', 'CLUSTER') }}"
    job_template: "{{ lookup('env', 'JOB_TEMPLATE') }}"
    extra_vars: "{{ lookup('file', 'environments/' + env + '/' + cluster + '/' + job_template + '.yml') | from_yaml }}"
  vars_files:
    - "common/vars.yml"
    - "dev/{{ env }}/{{ cluster }}/vars.yml"

  tasks:
    - name: "Ensure required variables are set"
      ansible.builtin.assert:
        that:
          - env is defined
          - cluster is defined
          - job_template is defined
        fail_msg: "Environment, cluster, and job template must be specified."

    - name: "Launch AAP Job Template {{ job_template }} for {{ env }} in cluster {{ cluster }}"
      ansible.builtin.include_role:
        name: infra.aap_configuration.controller_job_launch
      vars:
        name: "{{ job_template }}"
        organization: "{{ organization }}"
        extra_vars: "{{ extra_vars }}"
        wait: true
