---
- name: Launch AAP Job Template
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "common/vars.yml"
    - "environments/{{ env }}/{{ cluster }}/vars.yml"

  pre_tasks:
    - name: "Ensure required variables are set"
      ansible.builtin.assert:
        that:
          - env is defined
          - cluster is defined
          - job_template is defined
        fail_msg: "Environment, cluster, and job template must be specified."

    - name: Include vars for the job template
      ansible.builtin.include_vars:
        file: "environments/{{ env }}/{{ cluster }}/{{ job_template }}.yml"
        name: job_extra_vars

    - name: Debug variables
      ansible.builtin.debug:
        var: vars

  roles:
    - role: infra.aap_configuration.controller_job_launch
      vars:
        controller_launch_jobs:
          - name: "{{ job_template }}"
            organization: "{{ organization }}"
            extra_vars: "{{ job_extra_vars }}"
            wait: true
