---
name: Release

run-name: >
  ${{ github.workflow }} - Launch AAP Job Templates

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
        - 'environments/**/*.yml'
  push:
    branches:
      - main
    paths:
      - 'environments/**/*.yml'

permissions:
  contents: read

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed files using git
        id: detect-jobs
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"

          # Determine the comparison range based on event type (pull_request or push)
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            # For pull requests, compare against the target branch
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            HEAD_SHA="${{ github.event.pull_request.head.sha }}"
            echo "Comparing PR changes: $BASE_SHA..$HEAD_SHA"
            CHANGED_FILES=$(git diff --name-only "$BASE_SHA" "$HEAD_SHA")
          else
            # For push events, compare with the before SHA
            echo "Comparing push changes: ${{ github.event.before }}..${{ github.sha }}"
            CHANGED_FILES=$(git diff --name-only "${{ github.event.before }}" "${{ github.sha }}")
          fi

          echo "All changed files:"
          echo "$CHANGED_FILES"

          # Filter for relevant files (environments/**/*.yml but exclude vars.yml)
          RELEVANT_FILES=$(echo "$CHANGED_FILES" | grep -E '^environments/[^/]+/[^/]+/[^/]+\.yml$' | grep -Ev '^.*vars.yml$')

          echo "Relevant changed files: $RELEVANT_FILES"

          matrix_json=$(echo "$RELEVANT_FILES" | jq -Rn '[inputs | split("/") | { env: .[1], cluster: .[2], job: (.[3] | split(".") | .[0]) }]')
          echo "matrix=$matrix_json" >> $GITHUB_OUTPUT

      - name: Set matrix output
        id: set-matrix
        run: echo "matrix=${{ steps.detect-jobs.outputs.matrix }}" >> $GITHUB_OUTPUT

  launch-jobs:
    name: Launch Job Templates
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "ENV=${{ matrix.env }}" >> $GITHUB_ENV
          echo "CLUSTER=${{ matrix.cluster }}" >> $GITHUB_ENV
          echo "JOB=${{ matrix.job }}" >> $GITHUB_ENV

      - name: debug
        run: |
          echo "Environment: $ENV"
          echo "Cluster: $CLUSTER"
          echo "Job: $JOB"
